import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import vm from 'node:vm';
import type { Quad } from '@rdfjs/types';
import { DataFactory } from 'rdf-data-factory';
import { Writer } from 'rdf-writer-ts';
import { PrefixedWriter } from '../browser-src/prefixed-writer';
const df = new DataFactory();
const EX = 'https://example.org/', SCHEMA = 'https://schema.org/', XSD = 'http://www.w3.org/2001/XMLSchema#';
const quad = (s: string, p: string, value = df.literal('value')) => df.quad(df.namedNode(s), df.namedNode(p), value) as Quad;
function serialize(quads: Quad[], prefixes: Record<string, string> = {}) {
  const writer = new PrefixedWriter(new Writer());
  writer.addPrefixes(prefixes); writer.addQuads(quads);
  let output = ''; writer.end((error, result) => { if (error) throw error; output = result!; });
  return output;
}
async function main() {
  const output = serialize([quad(EX + 's', SCHEMA + 'name')], { mine: EX, vocabulary: SCHEMA, unused: 'urn:unused:' });
  assert.match(output, /@prefix mine:/); assert.match(output, /@prefix vocabulary:/);
  assert.match(output, /mine:s vocabulary:name/); assert.ok(!output.includes('unused') && !output.includes('@prefix schema:'));
  const fallback = serialize([quad(EX + 's', SCHEMA + 'name')]);
  assert.match(fallback, /@prefix schema: <https:\/\/schema.org\/>/);
  const conflict = serialize([quad(EX + 's', SCHEMA + 'name')], { schema: EX });
  assert.match(conflict, /schema:s schema2:name/);
  // Reserve source labels even when their namespace appears later in this batch.
  const later = serialize([quad('urn:s', SCHEMA + 'name'), quad(EX + 's', 'urn:p')], { schema: EX });
  assert.match(later, /@prefix schema2: <https:\/\/schema.org\/>/); assert.match(later, /@prefix schema: <https:\/\/example.org\/>/);
  const numeric = serialize([quad('urn:s', 'urn:p', df.literal('1.5', df.namedNode(XSD + 'decimal')))]);
  assert.ok(!numeric.includes('@prefix xsd:'));
  const date = serialize([quad('urn:s', 'urn:p', df.literal('2026-10-08', df.namedNode(XSD + 'date')))]);
  assert.match(date, /\^\^xsd:date/);
  assert.equal(serialize([], { mine: EX }), '', 'Unused prefixes must not create output for an empty graph.');
  const chunks: string[] = [];
  const stream = new PrefixedWriter(new Writer({ write: (chunk, _encoding, done) => { chunks.push(chunk); done?.(null); }, end: done => done?.(null) }, { rdfMessages: true }));
  stream.addPrefixes({ mine: EX });
  stream.addMessage([quad(EX + 'one', SCHEMA + 'name')]);
  stream.addPrefix('schema', 'https://other.example/');
  stream.addMessage([quad('https://other.example/two', SCHEMA + 'name')]);
  stream.end();
  const streamed = chunks.join('');
  assert.match(streamed, /@prefix schema2: <https:\/\/other.example\/>/);
  assert.equal((streamed.match(/@prefix schema: /g) ?? []).length, 1, 'A prefix already emitted must never be rebound.');
  const context = vm.createContext({ console, URL, AbortController, AbortSignal, TextEncoder, TextDecoder, setTimeout, clearTimeout, setInterval, clearInterval });
  context.self = context;
  vm.runInContext(readFileSync('browser/rdfjs-inference-engine.min.js', 'utf8'), context);
  const api = context.RdfjsInferenceEngine;
  const parsed = api.parseRdfOrMessages('@base <https://example.org/>. @prefix custom: <vocab#>. @prefix : <objects/>. :one custom:name "title".');
  assert.equal(parsed.prefixes.custom, 'https://example.org/vocab#');
  assert.equal(parsed.prefixes[''], 'https://example.org/objects/');
  const text = await api.writeQuads(parsed.quads, parsed.prefixes);
  assert.match(text, /:one custom:name/);
  const messages = api.parseRdfOrMessages('@prefix own: <https://example.org/>. VERSION "1.2-messages"\nown:one <https://schema.org/name> "one".\nMESSAGE\nown:two <https://schema.org/name> "two".');
  assert.equal(messages.prefixes.own, EX);
  const messageText = await api.writeMessages(messages.messages, messages.prefixes);
  assert.match(messageText, /own:one schema:name/); assert.match(messageText, /own:two schema:name/);
  assert.equal(api.parseRdfOrMessages(messageText).messages.length, 2);
  const roundTrip = api.parseRdfOrMessages(streamed);
  assert.equal(roundTrip.messages[1][0].subject.value, 'https://other.example/two');
  assert.equal(roundTrip.messages[1][0].predicate.value, SCHEMA + 'name');
  const defaults = new PrefixedWriter(new Writer({ rdfMessages: true }));
  defaults.addPrefix('', EX); defaults.addMessage([quad(EX + 'one', 'urn:p')]);
  defaults.addPrefix('', 'https://other.example/'); defaults.addMessage([quad('https://other.example/two', 'urn:p')]);
  let defaultText = ''; defaults.end((_error, output) => { defaultText = output!; });
  assert.match(defaultText, /@prefix ns2:/, 'Conflicting default prefixes receive a valid named alias.');
  assert.equal(api.parseRdfOrMessages(defaultText).messages[1][0].subject.value, 'https://other.example/two');
  const namedGraph = df.quad(df.namedNode(EX + 's'), df.namedNode(SCHEMA + 'name'), df.literal('title'), df.namedNode('https://graphs.example/g')) as Quad;
  const namedText = await api.writeMessages([[namedGraph]], { item: EX, graph: 'https://graphs.example/' });
  assert.match(namedText, /graph:g/);
  assert.equal(api.parseRdfOrMessages(namedText).quads[0].graph.value, 'https://graphs.example/g');
  console.log('Playground prefixes: source priority, prefix.cc fallback, used declarations, aliases, streaming, datatypes and message round-trips verified.');
}
void main().catch(error => { console.error(error); process.exitCode = 1; });
